services:
  high-link-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.nuxt
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  
      - HOST=0.0.0.0             
    env_file:
      - .env
    restart: unless-stopped
    networks:
        - high-link-network

  high-link-back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./back:/app
      - /app/node_modules
      - high-link-images:/app/images
    working_dir: /app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - high-link-mysql
      - high-link-mongodb
    restart: unless-stopped
    networks:
      - high-link-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "high-link-mysql"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  high-link-python:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - high-link-mongodb
    env_file:
      - .env
    volumes:
      - ./python:/app
      - ./python/images:/app/images
      - high-link-images:/app/images
    networks:
      - high-link-network

  high-link-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=highlink
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - high-link-mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - high-link-network

  high-link-adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - high-link-network

  high-link-mongodb:
    image: mongo
    container_name: high-link-mongodb
    ports:
      - "27017:27017"
    volumes:
      - high-link-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: unless-stopped
    networks:
      - high-link-network

  high-link-mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@high-link-mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
    restart: unless-stopped
    networks:
      - high-link-network

volumes:
  high-link-mysql-data:
  high-link-mongo-data:
  high-link-images:
  
networks:
  high-link-network:
    driver: bridge
